### ISSUE TITLE
No visible console logs during watch

### ISSUE THREAD

**Issue by samrith-s** [formium/tsdx#930] opened 2020-11-08 15:19 UTC
### Current Behavior

I have the following code:
![image](https://user-images.githubusercontent.com/9032162/98469085-eba6d380-21dd-11eb-8377-03acf93a3b1e.png)

But when in watch mode, I do not get an console logs:
![image](https://user-images.githubusercontent.com/9032162/98469097-fb261c80-21dd-11eb-847d-0e8a75da8718.png)

### Expected behavior

It should print console log statements in code on the terminal.

### Your environment

```text
  System:
    OS: macOS 10.15.6
    CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
    Memory: 7.94 GB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.6.0 - ~/.nvm/versions/node/v14.6.0/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v14.6.0/bin/yarn
    npm: 6.14.6 - ~/.nvm/versions/node/v14.6.0/bin/npm
  Browsers:
    Chrome Canary: 88.0.4319.0
    Safari: 13.1.2
  npmPackages:
    tsdx: 0.14.1 => 0.14.1
    typescript: 4.0.5 => 4.0.5
```

**Comment by agilgur5** [comment] 2020-11-08 16:41
Duplicate of #478

**Closed by agilgur5** 2020-11-08 16:41 UTC
