### ISSUE TITLE
Move typescript compilation to esbuild and run babel on the output

### ISSUE THREAD

**Issue by jaredpalmer** [formium/tsdx#859] opened 2020-09-17 01:08 UTC
### Current Behavior

Tsdx doesn’t correctly transpile typescript thanks to upstream issues with Babel transform async to promises. The project appears to be dead. 

### Desired Behavior

Tsdx transpires typescript perfectly.

### Suggested Solution

Write our own typescript rollup plugin that uses esbuild

### Who does this impact? Who is this for?

Everyone

### Additional context

I spoke with Evan You (inventor of Vue.js) privately about how he uses esbuild to power vite. He shared this technique with me. Basically, esbuild is really really really good and fast for typescript compilation. Its minifier, however, is significantly worse than terser according to Evan’s benchmarks. Thus, he suggested we implement it as a custom rollup plugin and keep the rest of the rollup pipeline for assets etc. Vite doesn’t use babel, however, we could still support it by running it after transpilation. Lastly, esbuild doesn’t type check, so we will want to take care of type checking on build and on watch. 

On my phone right now, but this relates to several 
 open issues. Feel free to update this with more. #684 #795

**Comment by agilgur5** [comment] 2020-09-17 01:36
Duplicate of #716, which I've already addressed in detail

> Tsdx doesn’t correctly transpile typescript thanks to upstream issues with Babel transform async to promises. The project appears to be dead.

This is unrelated to ESBuild -- I don't believe it polyfills generators, and compiles async to generators, sometimes incorrectly as well: https://github.com/evanw/esbuild/issues/388.

In any case that duplicates several existing issues and a PR. It is already being worked on and I've already responded to all the relevant issues and [labeled them](https://github.com/formium/tsdx/issues?q=is%3Aopen+is%3Aissue+label%3Atopic%2Fasync-to-promises). It is slated to be fixed in [v0.14.0](https://github.com/formium/tsdx/milestone/2) which I'm planning to release quite soon and am planning to finish #795 myself. Also not that many users are impacted by this bug, I've been tracking it for a while here and in `microbundle`.

Please search the issues before filing duplicates.

**Closed by agilgur5** 2020-09-17 01:36 UTC
