### ISSUE TITLE
How to disable `eslint-config-react-app`?

### ISSUE THREAD

**Issue by NARUTOne** [formium/tsdx#907] opened 2020-10-16 10:50 UTC
### Current Behavior

`React Hook "useCompose" is called in function "getWidgetProps" that is neither a React function component nor a custom React Hook function.eslint(react-hooks/rules-of-hooks)`

### Desired Behavior

Don't tip. This is only function. The current project is a pure library of tools using Typescript

It doesn't work.

```js
module.exports = {
  "extends": [
    // "react-app",
    "prettier/@typescript-eslint",
    "plugin:prettier/recommended"
  ],
  "settings": {
    // "react": {
    //   "version": "999.999.999"
    // }
  }
}
```

**Comment by agilgur5** [comment] 2020-10-16 16:23
Based on the names of your functions (`useCompose` and `getWidgetProps`, it sounds like you're writing a library _for_ React components, is that not correct? If so, I'd certainly recommend following the official hooks lint rules. `getWidgetProps` doesn't follow hook naming conventions, which is why you're getting the error; I'd recommend naming it appropriately.

If you really want to disable a rule for that particular function, you can use an [ESLint inline ignore](https://eslint.org/docs/user-guide/configuring#disabling-rules-with-inline-comments) for that.

If you're _not_ writing for usage in React, which isn't really clear as you didn't provide any repro, then yes you're hitting a known issue with the way the ESLint API's merging works. This would be a duplicate of #514 which is a duplicate of #498. In https://github.com/formium/tsdx/issues/498#issuecomment-583244717 I described how to disable rules using [ESLint configuration](https://eslint.org/docs/user-guide/configuring), which you can similarly use for this (just different rules).

If you use `package.json#eslintConfig` instead of an `eslintrc`, that uses a shallow merge and so your config that you've written here should work in `package.json#eslintConfig`.

**Closed** 2020-10-16 16:25 UTC
Labels: kind: support, problem: removed issue template, solution: duplicate, solution: workaround available

**Comment by agilgur5** [comment] 2020-10-16 16:35
Also, if you set `react` to `999.999.999` that should disable all React rules per #308 . You've commented out `settings.react`; you should uncomment that if you're not writing for React.
