### ISSUE TITLE
Add Preact’s bundle size GH action to all templates

### ISSUE THREAD

**Issue by jaredpalmer** [formium/tsdx#841] opened 2020-08-28 20:37 UTC
Seems like everyone will want this https://github.com/preactjs/compressed-size-action

**Comment by agilgur5** [comment] 2020-08-29 00:38
Duplicate of #496 / #741. And there's already a PR #705 that uses `size-limit` and adds commands and a GH action to the templates and has gone through some iterations (probably just about ready to merge).

@jaredpalmer would appreciate if you could also fill out the issue template and not make exceptions.

**Closed by agilgur5** 2020-08-29 00:38 UTC
Labels: duplicate, feature, removed issue template
