### ISSUE TITLE
Using Example App, CSS Modules aren't included

### ISSUE THREAD

**Issue by stephencweiss** [formium/tsdx#1015] opened 2021-04-20 12:53 UTC
### Current Behavior

My application is using CSS Modules. These are being exported correctly with the following `tsdx.config.js`:
```javascript
const postcss = require('rollup-plugin-postcss');
const autoprefixer = require('autoprefixer');
const cssnano = require('cssnano');
const tailwindcss = require('tailwindcss');

module.exports = {
  rollup(config, options) {
    config.plugins.push(
      postcss({
        plugins: [
          autoprefixer(),
          tailwindcss(),
          cssnano({
            preset: 'default',
          }),
        ],
        inject: false,
        // only write out CSS for the first bundle (avoids pointless extra files):
        extract: !!options.writeMeta,
      })
    );
    // config.external = ['react', 'react-dom']
    return config;
  },
};
```
You can see the modules are being properly placed in the built `.css` file:
![Screen Shot 2021-04-20 at 7 46 01 AM](https://user-images.githubusercontent.com/39878535/115398289-a0411a00-a1ac-11eb-9901-a56f02c7d53c.png)

However, when I run the example app, while the classes are being applied, the style sheet seems to be missing and so no actual CSS properties are being attached.

![Screen Shot 2021-04-20 at 7 46 58 AM](https://user-images.githubusercontent.com/39878535/115398293-a0d9b080-a1ac-11eb-8e51-dcd3399ec2df.png)

I've tried adding a `postcssrc` (and `postcss.config.js`) like so: 
```javascript
const postcss = require('postcss-modules');
const autoprefixer = require('autoprefixer');
const cssnano = require('cssnano');
const tailwindcss = require('tailwindcss');


module.exports = {
  modules: true,
  plugins: [
    autoprefixer(),
    tailwindcss(),
    cssnano({
      preset: 'default',
    }),
  ],
  inject: false,
};
```

### Expected behavior

The styles are applied because the stylesheet is included in the parcel bundle.

### Suggested solution(s)

An example of how to make better use of the example app so that it mirrors that exported assets would be appreciated.

### Your environment

```text
System:
    OS: macOS 10.15.7
    CPU: (16) x64 Intel(R) Core(TM) i9-9980HK CPU @ 2.40GHz
    Memory: 130.66 MB / 32.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 14.16.0 - ~/.volta/tools/image/node/14.16.0/bin/node
    Yarn: 1.22.4 - ~/.volta/tools/image/yarn/1.22.4/bin/yarn
    npm: 6.14.11 - ~/.volta/tools/image/node/14.16.0/bin/npm
  Browsers:
    Brave Browser: 90.1.23.71
    Chrome: 90.0.4430.72
    Firefox: 87.0
    Safari: 14.0.3
    Safari Technology Preview: 14.2
  npmPackages:
    tsdx: ^0.14.1 => 0.14.1 
    typescript: ^4.2.3 => 4.2.3 
```

**Comment by agilgur5** [comment] 2021-04-21 22:28
Sounds like a duplicate of #959 which is mostly a duplicate of https://github.com/formium/tsdx/discussions/947#discussioncomment-224566

**Closed by agilgur5** 2021-04-21 22:28 UTC
Labels: kind: support, scope: integration, solution: duplicate, solution: intended behavior

**Comment by stephencweiss** [comment] 2021-04-21 23:08
Thanks @agilgur5 ! Apologies for the duplicate.
