### ISSUE TITLE
Test command failures due to type-checking

### ISSUE THREAD

**Issue by ImanMh** [formium/tsdx#937] opened 2020-11-14 16:21 UTC
### Current Behavior

A simple lint issue can stop `npm run test`. Do we really need to fix every single lint issue before running npm run test? Cause many times I want to try things out just to see if they work so I don't care about lint issues at that moment.

<img width="1056" alt="Screen Shot 2020-11-14 at 7 44 12 PM" src="https://user-images.githubusercontent.com/4482199/99151740-66765f80-26b2-11eb-99df-7fe7ab1551d7.png">

### Expected behavior

I'd rather see lint issues and then test results.

**Comment by agilgur5** [comment] 2020-11-14 17:12
Those aren't lint issues -- they are `TS` codes, i.e. they are type-checking errors.

This is a key feature of `ts-jest`, but yes, you can turn it off. Duplicate of #681

**Closed by agilgur5** 2020-11-14 17:12 UTC
