### ISSUE TITLE
"No valid exports main found for..." when try to create

### ISSUE THREAD

**Issue by scink** [formium/tsdx#747] opened 2020-06-17 16:04 UTC
trying to create via 'npx tsdx create projectname'

### Current Behavior

see the error `No valid exports main found for '/Users/anton/.npm/_npx/33468/lib/node_modules/tsdx/node_modules/@rollup/pluginutils'`

### Expected behavior

no error

### Suggested solution(s)

???

### Additional context

-
### Your environment

| Software         | Version(s) |
| ---------------- | ---------- |
| TSDX           | not installed
| TypeScript       | no global typescript
| Browser          | doesn't matter
| npm/Yarn         | 6.13.4/1.22.4
| Node             | 12.18.0/13.11.0/14.4.0 (tried with each of them)
| Operating System | macos catalina 10.15.4

**Comment by agilgur5** [comment] 2020-06-17 19:16
Per your logging, this sounds like an issue in `@rollup/pluginutils` and not here. TSDX doesn't even depend on it directly, it seems to be a transitive dep of the one of the Rollup deps, so not easy to pin to fix.

`@rollup/pluginutils` seems to have a `main` field in the `package.json`, but [a recent change](https://github.com/rollup/plugins/blob/f215c2542282af5db34c88a8f80357d2c33ee956/blame/packages/pluginutils/package.json#L78) added conditional exports support which I guess has a bug.

I can't remember if conditional exports are only in Node v13+ or if they are in v12 also. Node v10 should work if that's the case then.

**Comment by scink** [comment] 2020-06-18 14:07
@agilgur5, node v10 did work, thank you!

**Comment by rikoe** [comment] 2020-07-16 10:43
Is there any update on this issue? None of the TSDX commands work if you are running any of the node versions after 10, which makes it really hard to use for my team - the latest stable Node is v12, so v10 is really quite old now, and most people have moved on. Is there a temporary workaround that can be applied to the TSDX package to protect users from these errors?

**Comment by jaredpalmer** [comment] 2020-07-16 12:14
I use tsdx with node 12 on my Mac. Will try this out this am

**Comment by agilgur5** [comment] 2020-07-16 14:09
@rikoe @jaredpalmer as has been written, this is not a TSDX issue, it is upstream in `@rollup/pluginutils`, and not even a direct dependency at that. I left this open as I still need to further investigate on their side to figure out an issue or PR to file against them. If this is still an issue and you want to resolve it, I would suggest going upstream to the source.

> the latest stable Node is v12

That's not correct, [Node v10 is LTS for another year](https://nodejs.org/en/about/releases/). Maybe you're thinking Node v8.

**Comment by rikoe** [comment] 2020-07-16 14:48
@agilgur5 sorry I don't mean Node 10 is out of LTS, just that v12 is the most recent LTS version on Node's website.

I *think* the related issue at rollup is https://github.com/rollup/rollup/issues/3427.

They mention upgrading to Node v13.8 or higher, and this has indeed fixed the issue for me (although the original post said it didn't work for 12.18.0/13.11.0/14.4.0?). I was on 13.5.0 before. It seems therefore that the workaround above (downgrade to v10) is a bit drastic, it does work for other newer versions too.

It looks like https://github.com/rollup/rollup/pull/3428 was merged and included in rollup 2.0.2 to address the issue?

This issue also seems to indicate that the problem is related to specific Node 13 point releases: https://github.com/rollup/plugins/issues/473

**Comment by agilgur5** [comment] 2020-07-18 02:55
@rikoe Ah well if that's the issue then this is the same as https://github.com/formium/tsdx/issues/630, which points to upstream https://github.com/nodejs/node/issues/32107. But the two Rollup issues linked are in Rollup itself, which isn't what's giving the error, the plugin issue https://github.com/rollup/plugins/issues/473 is. Rollup and others seem to have created workarounds for Node v13.0-v13.7 so I'm not sure why `pluginutils` hasn't used the same one.

But yes OP's 12.18.0/13.11.0/14.4.0 would suggest that these are perhaps different issues we're talking about. In any case, will close this out for now since you and OP have found solutions. Can open back up if it pops up again though would point upstream.

**Closed by agilgur5** 2020-07-18 02:55 UTC
Labels: upstream, workaround available
